### ISSUE TITLE
io error: failed to fill whole buffer

### ISSUE THREAD

**Issue by classclass2** [mathwallet/SolanaSwift#6]
```public func sendTransaction(base58:String,successBlock:@escaping (_ transaferHash:String)-> Void,failure:@escaping (_ error:Error)-> Void) {
        self.sendJsonRpc(method: "sendTransaction", resultType: String.self, parameters: [base58]) { data in
            successBlock(data)
        } failure: { error in
            failure(error)
        }
    }
```
When i sign an transation and broadcast this base58 string ```7cLaa5P2dxmXqT9wmnAWePZdEUF8SWi1rc9eRkPKp5Ujw5gDHSLaFTo3KBc9nzsJGpFgwFJqq6VTd1qZuRLjdFJ```

i got an error:
```io error: failed to fill whole buffer```

What should i do ? Thanks very much.

**Comment by xueyuejie** [comment]
You should to check your base data before encoded ,Your data format is wrong
